config/routes.rb
Models::Application.routes.draw do
  get "sessions/new"
  get "home/index"
  get "members/new"
  get "pages/home"

    resources :members
	resources :sessions, :only => [:new, :create, :destroy]
	resources :items, :only => [:create, :destroy, :index]
	match '/signup', :to=>'members#new'
	match '/signin',  :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'

   root :to => "pages#home"

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :status, :condition, :price_set, :category_name, :seller_id, :buyer_id
  
  belongs_to :member, :foreign_key => 'seller_id'
  belongs_to :member, :foreign_key => 'buyer_id'
  belongs_to :category
  has_many :bidding_periods, :dependent => :destroy
  has_many :bidder_period_items, :dependent => :destroy	
  
  validates :name, :presence=>true, :length => { :maximum => 50}
  validates :condition, :presence=>true, :length => { :maximum => 15}
  validates :price_set, :presence=>true
  validates :category_name, :presence=>true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_filter :authenticate, :only=>[:create, :destroy]

  def index
	@items1 = Item.where(:category_name => params[:category_name])
	@items_found = @items1
	render 
  end
  
  
  def new
	@auction_item = Item.new
	
	respond_to do |format|
		format.html  # addAuctionItem.html.erb
		format.json  { render :json => @auction_item }
    end
  end
  
  
  def create
    @item  = current_member.items.build(params[:item])
	@item.seller_id = current_member.id
	@item.status = 1
	@item.category_name = 'Electronics'
	@item.buyer_id = 0
    if @item.save
      flash[:success] = "Item up for auction !"
      redirect_to current_member
    else
      render 'pages/home'
    end
  end
  
  
  def show
	@item = Item.find(params[:id])
 
	respond_to do |format|
		format.html  # show.html.erb
		format.json  { render :json => @item }
	end
  end
  
  
  def destroy
	@item = Item.find(params[:id])
	@item.destroy
 
	respond_to do |format|
		format.html { redirect_to items_url }
		format.json { head :ok }
	end
  end
end
  

app/views/items/_item.html.erb
<tr>
  <td class="item">
    <span class="content"><%= item.name %></span>
	<span class="content"><%= item.category_name %></span>
	<span class="content"><%= item.status %></span>
	<span class="content"><%= item.condition %></span>
	<span class="content"><%= item.price_set %></span>
    <span class="timestamp">
      Created <%= time_ago_in_words(item.created_at) %> ago.
    </span>
  </td>
</tr>

app/views/items/index.html.erb
<h4>Welcome <%= current_member.first_name %> !</h4> <br>
<h5> Search Results </h5>

<table class="search">
  <tr>
    <td class="main">
	   <% unless @items1.empty? %>
          <table class="items" summary="Items in the given category">
             <%= render @items_found %>
          </table>
      <% end %>
	</td>
  </tr>
</table>

<%= link_to "Settings", edit_member_path(current_member) %> <br />
<%= link_to "Sign out", signout_path, :method=> :delete %> 
